# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170531_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='hosted_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
